<template>
  <div>
    <b-row>
      <h1>Vessels Rules Explorer</h1>
      <p></p>
    </b-row>
    <b-row>
      <b-col>
        <p>This interface allows the exploration of a the rules generated by different neighborhoods around
          a given instance.
        Use the form below to insert the values of the instance to be used as seed for the generation. The
        parameters for the neighborhood generation can be defined at the bottom.</p>
      </b-col>
    </b-row>
    <b-row>
      <b-col>
        <VesselsForm @sendRequest="sendRequest"/>
      </b-col>
    </b-row>
    <b-row>
      <b-col>
        <h5>Predicted class: {{spec["predicted_class"]}}</h5>
      </b-col>
    </b-row>
    <b-row>
      <b-col>
        <h3>Explanations</h3>
        <hr/>
      </b-col>
    </b-row>
    <b-row>
      <b-col v-for="(v,k) in spec['explanations']" :key="k">
        <h4>{{k}}</h4>
        <hr/>
        <h5>Rule</h5>
        <RuleViz :rule="v['rule']"/>
        <hr/>
        <h5>Counterrules</h5>
        <RuleViz v-for="(c,l) in v['counterfactuals']" :key='l' :rule="c"/>
      </b-col>
    </b-row>
  </div>
</template>

<script>
import VesselsForm from './VesselsForm';
import RuleViz from "./RuleViz";

export default {
  name: 'VesselsRules',
  components: {
    VesselsForm,
    RuleViz
  },
  data() {
    return {

      contentValue: '',
      spec: {
        instance: [
          0,
          0,
          0,
          0,
          52.4,
          0,
          0,
          0,
          0,
        ],
        predicted_class: '',
        explanations: {

        },
      },
    };
  },
  methods: {
    sendRequest(strPayload) {
      console.log('payload', strPayload);
      const strValue = strPayload;

      fetch('http://localhost:10000/api/vessels/explain', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: strValue,
      })
        .then(response => response.json())
        .then((data) => {
          this.spec = data;
          // Render the visualization
          // embed('#viz', data, { mode: 'vega-lite' });
        },
        ).catch((error) => {
          alert('There was an error processing your request');
        });
    },
  },
};
</script>

<style scoped>

</style>
